import SwiftUI

#Preview { ChangelogView() }

/// "What's New" sheet. Renders the build-time-baked `CHANGELOG.md`
/// (`ChangelogData.markdown`, generated by `make changelog`) as one expandable
/// card per version. The latest version (first in the file) starts expanded.
struct ChangelogView: View {
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 12) {
                    ForEach(Self.versions) { v in
                        ChangelogCard(version: v, isLatest: v.id == 0)
                    }
                }
                .padding()
            }
            .navigationTitle("What's New")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
    }

    // MARK: - Parsing

    struct Version: Identifiable {
        let id: Int
        let title: String
        let bodyLines: [String]
    }

    /// Split the markdown into versions on each level-2 (`## `) heading. The top
    /// "# Changelog" + intro paragraph sits before the first one and is dropped.
    static var versions: [Version] {
        var out: [Version] = []
        var title: String?
        var body: [String] = []
        func flush() {
            if let title { out.append(.init(id: out.count, title: title, bodyLines: body)) }
            body = []
        }
        for raw in ChangelogData.markdown.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(raw)
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("## ") {
                flush()
                title = String(trimmed.dropFirst(3))
                    .replacingOccurrences(of: "[", with: "")
                    .replacingOccurrences(of: "]", with: "")
            } else if title != nil {
                body.append(line)
            }
        }
        flush()
        return out
    }
}

/// A single expandable version card: tappable header (version + date + chevron)
/// over an animated body. CHANGELOG.md hard-wraps bullets across several source
/// lines, so the parser reflows continuation lines back into their bullet before
/// rendering; `AttributedString(markdown:)` styles inline **bold** / `code` / links.
private struct ChangelogCard: View {
    let version: ChangelogView.Version
    let isLatest: Bool
    @State private var expanded: Bool

    init(version: ChangelogView.Version, isLatest: Bool) {
        self.version = version
        self.isLatest = isLatest
        _expanded = State(initialValue: isLatest)
    }

    private enum Block {
        case section(String)            // "Added" / "Changed" / "Fixed" / …
        case bullet(AttributedString)
        case paragraph(AttributedString)
    }

    /// Reflow the hard-wrapped body into logical blocks. A line that is neither
    /// blank, a `###` section, nor a new `- ` bullet is a wrapped continuation and
    /// gets appended to whatever block is open.
    private var blocks: [Block] {
        var out: [Block] = []
        var buf: String?
        var bufIsBullet = false
        func flush() {
            guard let t = buf else { return }
            out.append(bufIsBullet ? .bullet(inline(t)) : .paragraph(inline(t)))
            buf = nil
        }
        for line in version.bodyLines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { flush(); continue }
            if trimmed.hasPrefix("### ") {
                flush(); out.append(.section(String(trimmed.dropFirst(4)))); continue
            }
            if trimmed.hasPrefix("- ") || trimmed.hasPrefix("* ") {
                flush(); buf = String(trimmed.dropFirst(2)); bufIsBullet = true; continue
            }
            if buf != nil { buf! += " " + trimmed }
            else { buf = trimmed; bufIsBullet = false }
        }
        flush()
        return out
    }

    private func inline(_ s: String) -> AttributedString {
        (try? AttributedString(
            markdown: s,
            options: .init(interpretedSyntax: .inlineOnlyPreservingWhitespace)
        )) ?? AttributedString(s)
    }

    /// "1.0.0 - Unreleased" → ("1.0.0", "Unreleased").
    private var versionParts: (number: String, date: String?) {
        let parts = version.title.components(separatedBy: " - ")
        return (parts.first ?? version.title, parts.count > 1 ? parts[1] : nil)
    }

    /// Subtle semantic colour per Keep-a-Changelog group.
    private func sectionColor(_ name: String) -> Color {
        switch name.lowercased() {
        case "added": return .green
        case "changed": return .blue
        case "fixed": return .orange
        case let s where s.hasPrefix("security"): return .purple
        case "removed", "deprecated": return .red
        default: return .secondary
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header
            if expanded {
                Divider().opacity(0.5).padding(.horizontal, 14)
                content
                    .padding(14)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .transition(.opacity)
            }
        }
        .background(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .fill(Color(.secondarySystemBackground))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .strokeBorder(isLatest ? AnyShapeStyle(.tint.opacity(0.45))
                                       : AnyShapeStyle(.primary.opacity(0.08)),
                              lineWidth: 1)
        )
        .clipShape(RoundedRectangle(cornerRadius: 16, style: .continuous))
    }

    private var header: some View {
        Button {
            withAnimation(.snappy(duration: 0.28)) { expanded.toggle() }
        } label: {
            HStack(spacing: 8) {
                Text(versionParts.number)
                    .font(.headline)
                    .foregroundStyle(.primary)
                if let date = versionParts.date {
                    Text(date)
                        .font(.caption.weight(.medium))
                        .foregroundStyle(.secondary)
                }
                if isLatest {
                    Text("LATEST")
                        .font(.caption2.weight(.bold))
                        .tracking(0.5)
                        .foregroundStyle(.tint)
                        .padding(.horizontal, 6).padding(.vertical, 2)
                        .background(RoundedRectangle(cornerRadius: 6, style: .continuous)
                            .fill(.tint.opacity(0.15)))
                }
                Spacer()
                Image(systemName: "chevron.down")
                    .font(.caption.weight(.bold))
                    .foregroundStyle(.secondary)
                    .rotationEffect(.degrees(expanded ? 0 : -90))
            }
            .padding(14)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }

    @ViewBuilder private var content: some View {
        VStack(alignment: .leading, spacing: 7) {
            ForEach(Array(blocks.enumerated()), id: \.offset) { _, block in
                switch block {
                case .section(let s):
                    HStack(spacing: 6) {
                        Circle().fill(sectionColor(s)).frame(width: 6, height: 6)
                        Text(s.uppercased())
                            .font(.caption2.weight(.bold))
                            .tracking(0.8)
                            .foregroundStyle(sectionColor(s))
                    }
                    .padding(.top, 10)
                case .bullet(let a):
                    HStack(alignment: .firstTextBaseline, spacing: 8) {
                        Circle().fill(.tertiary).frame(width: 4, height: 4)
                            .padding(.top, 6)
                        Text(a)
                            .font(.callout)
                            .foregroundStyle(.primary.opacity(0.85))
                            .fixedSize(horizontal: false, vertical: true)
                    }
                case .paragraph(let a):
                    Text(a)
                        .font(.callout)
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }
}
